### ISSUE TITLE
Merge this repo with main scio repo

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/scio-template.g8#1]
Once giter8 0.8.0 is supported in sbt merge this repo with main scio repo and use subdirectory template feature.

**Comment by nevillelyh** [comment]
https://github.com/foundweekends/giter8/releases
Latest is 0.9.0, should we do this?

**Comment by ravwojdyla** [comment]
@nevillelyh we need [this](https://github.com/sbt/sbt-giter8-resolver/pull/8) merged first.

**Comment by ravwojdyla** [comment]
link https://github.com/sbt/sbt-giter8-resolver/issues/11

**Comment by regadas** [comment]
As per discussion with @ravwojdyla we decided that we will keep the template separate from the main repo.
